// installing package.json
// installing express
// creating file index.js
// import express
// usig expreess creating server app
// set up port number to the server app
// running command node space index point
// user request resolving
// post request  start doing on thunderclient
// services floder =>data services file
    // register function calling
  // importing dataservices
    // export  files in in dataservices 
     // data to body .req json format
    // assign to const variable  for return response
    // jwt Token
// jwt token is using for user validation
// token generation
// token verify
// npm i jsonwebtoken
// for token generate we using method -sign()
// for  verify  the token we using  -verify()

middlewares-
creating middlewares
three argument